workflows:
  android-release:
    name: Camera Parent Android APK

    environment:
      flutter: stable

    scripts:
      - name: Clean Flutter
        script: |
          flutter clean

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
